source env/Scripts/activate
python src/pit/attack.py -m uae -t 8 -th 5 -ht 5 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-5-8-5.log
python src/pit/attack.py -m uae -t 8 -th 6 -ht 5 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-5-8-6.log
python src/pit/attack.py -m uae -t 9 -th 5 -ht 5 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-5-9-5.log
python src/pit/attack.py -m uae -t 9 -th 6 -ht 5 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-5-9-6.log
python src/pit/attack.py -m uae -t 10 -th 5 -ht 5 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-5-10-5.log
python src/pit/attack.py -m uae -t 10 -th 6 -ht 5 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-5-10-6.log
python src/pit/attack.py -m uae -t 8 -th 5 -ht 5 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-5-8-5.log
python src/pit/attack.py -m uae -t 8 -th 6 -ht 10 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-10-8-6.log
python src/pit/attack.py -m uae -t 9 -th 5 -ht 10 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-10-9-5.log
python src/pit/attack.py -m uae -t 9 -th 6 -ht 10 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-10-9-6.log
python src/pit/attack.py -m uae -t 10 -th 5 -ht 10 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-10-10-5.log
python src/pit/attack.py -m uae -t 10 -th 6 -ht 10 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-10-10-6.log
python src/pit/attack.py -m uae -t 8 -th 6 -ht 20 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-20-8-6.log
python src/pit/attack.py -m uae -t 9 -th 5 -ht 20 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-20-9-5.log
python src/pit/attack.py -m uae -t 9 -th 6 -ht 20 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-20-9-6.log
python src/pit/attack.py -m uae -t 10 -th 5 -ht 20 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-20-10-5.log
python src/pit/attack.py -m uae -t 10 -th 6 -ht 20 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-20-10-6.log
python src/pit/attack.py -m uae -t 8 -th 6 -ht 40 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-40-8-6.log
python src/pit/attack.py -m uae -t 9 -th 5 -ht 40 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-40-9-5.log
python src/pit/attack.py -m uae -t 9 -th 6 -ht 40 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-40-9-6.log
python src/pit/attack.py -m uae -t 10 -th 5 -ht 40 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-40-10-5.log
python src/pit/attack.py -m uae -t 10 -th 6 -ht 40 -d dataset/pompa-attack-2.csv > logs/pit/test/uae-40-10-6.log